//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18449
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OvulationCalendar {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OvulationCalendar.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить месячные.
        /// </summary>
        internal static string AddMenses {
            get {
                return ResourceManager.GetString("AddMenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нужно перезапустить программу, чтобы изменения вступили в силу.
        /// </summary>
        internal static string AppRestartingRequired {
            get {
                return ResourceManager.GetString("AppRestartingRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Апрель.
        /// </summary>
        internal static string April {
            get {
                return ResourceManager.GetString("April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Август.
        /// </summary>
        internal static string August {
            get {
                return ResourceManager.GetString("August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Программа не может создать файл настроек.
        /// </summary>
        internal static string CannotCreateDataBaseFile {
            get {
                return ResourceManager.GetString("CannotCreateDataBaseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удается удалить файл базы данных пользователя..
        /// </summary>
        internal static string CannotDelDatabaseFile {
            get {
                return ResourceManager.GetString("CannotDelDatabaseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Программа не может открыть файл с именами пользователей.
        /// </summary>
        internal static string CannotOpenUserNamesFile {
            get {
                return ResourceManager.GetString("CannotOpenUserNamesFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось сохранить настройки в файл.
        /// </summary>
        internal static string CannotSaveSettings {
            get {
                return ResourceManager.GetString("CannotSaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить месячные.
        /// </summary>
        internal static string ChangeMenses {
            get {
                return ResourceManager.GetString("ChangeMenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменение цикла.
        /// </summary>
        internal static string CycleChanging {
            get {
                return ResourceManager.GetString("CycleChanging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Декабрь.
        /// </summary>
        internal static string December {
            get {
                return ResourceManager.GetString("December", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполнено.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на прекр.
        /// </summary>
        internal static string endin {
            get {
                return ResourceManager.GetString("endin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пока есть незакрытый цикл,
        ///позже него новые вводить нельзя.
        /// </summary>
        internal static string Err_CannotCreateNewCycleWhileOldOneIsNotEnded {
            get {
                return ResourceManager.GetString("Err_CannotCreateNewCycleWhileOldOneIsNotEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введенный цикл совпадает или
        ///пересекается с уже существующим.
        /// </summary>
        internal static string Err_CycleIsOverlappedWithExisting {
            get {
                return ResourceManager.GetString("Err_CycleIsOverlappedWithExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введен слишком длинный цикл.
        /// </summary>
        internal static string Err_CycleIsTooLong {
            get {
                return ResourceManager.GetString("Err_CycleIsTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Длина цикла должна быть
        ///больше одного дня.
        /// </summary>
        internal static string Err_CycleShuldBeLongerThanOneDay {
            get {
                return ResourceManager.GetString("Err_CycleShuldBeLongerThanOneDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Конец цикла не может быть раньше начала.
        /// </summary>
        internal static string Err_EndIsEarlierThanBegin {
            get {
                return ResourceManager.GetString("Err_EndIsEarlierThanBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый диапазон пересекается с другим циклом.
        /// </summary>
        internal static string Err_NewRangeIsOverlappingWithOtherCycle {
            get {
                return ResourceManager.GetString("Err_NewRangeIsOverlappingWithOtherCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Один неоконченный цикл уже введен.
        /// </summary>
        internal static string Err_OneNotEndedCycleAlreadyExist {
            get {
                return ResourceManager.GetString("Err_OneNotEndedCycleAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Между циклами не должно быть меньше 10 дней.
        /// </summary>
        internal static string Err_ShouldBeMoreThan10daysBetweenCycles {
            get {
                return ResourceManager.GetString("Err_ShouldBeMoreThan10daysBetweenCycles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разработчик программы обоснованно предполагает,
        ///что планировать цикл так далеко не имеет смысла.
        /// </summary>
        internal static string Err_TheCycleIsTooFar {
            get {
                return ResourceManager.GetString("Err_TheCycleIsTooFar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введена слишком старая дата для цикла,
        ///который еще не закончен.
        /// </summary>
        internal static string Err_TooOldDateForNotCompleteCycle {
            get {
                return ResourceManager.GetString("Err_TooOldDateForNotCompleteCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Год должен быть в пределах.
        /// </summary>
        internal static string Err_YearShouldBeInRange {
            get {
                return ResourceManager.GetString("Err_YearShouldBeInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неудачно.
        /// </summary>
        internal static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Февраль.
        /// </summary>
        internal static string February {
            get {
                return ResourceManager.GetString("February", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пт.
        /// </summary>
        internal static string Fri {
            get {
                return ResourceManager.GetString("Fri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Январь.
        /// </summary>
        internal static string January {
            get {
                return ResourceManager.GetString("January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Июль.
        /// </summary>
        internal static string July {
            get {
                return ResourceManager.GetString("July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Июнь.
        /// </summary>
        internal static string June {
            get {
                return ResourceManager.GetString("June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Март.
        /// </summary>
        internal static string March {
            get {
                return ResourceManager.GetString("March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Май.
        /// </summary>
        internal static string May {
            get {
                return ResourceManager.GetString("May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на менстр.
        /// </summary>
        internal static string mens {
            get {
                return ResourceManager.GetString("mens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вероятность прекращения {0}%.
        /// </summary>
        internal static string MensesEndProbability {
            get {
                return ResourceManager.GetString("MensesEndProbability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вероятность начала менструации {0}%.
        /// </summary>
        internal static string MensesProbability {
            get {
                return ResourceManager.GetString("MensesProbability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пн.
        /// </summary>
        internal static string Mon {
            get {
                return ResourceManager.GetString("Mon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь был создан и активирован.
        /// </summary>
        internal static string NewUserCreateSuccess {
            get {
                return ResourceManager.GetString("NewUserCreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Видимо отсутствует доступ к файловой системе.
        /// </summary>
        internal static string NoAccessToFile {
            get {
                return ResourceManager.GetString("NoAccessToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на н/д.
        /// </summary>
        internal static string notAvailable {
            get {
                return ResourceManager.GetString("notAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ноябрь.
        /// </summary>
        internal static string November {
            get {
                return ResourceManager.GetString("November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Октяпбрь.
        /// </summary>
        internal static string October {
            get {
                return ResourceManager.GetString("October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на овул.
        /// </summary>
        internal static string ovul {
            get {
                return ResourceManager.GetString("ovul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вероятность начала овуляции {0}%.
        /// </summary>
        internal static string OvulationProbability {
            get {
                return ResourceManager.GetString("OvulationProbability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить месячные.
        /// </summary>
        internal static string RemoveMenses {
            get {
                return ResourceManager.GetString("RemoveMenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сб.
        /// </summary>
        internal static string Sat {
            get {
                return ResourceManager.GetString("Sat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сентябрь.
        /// </summary>
        internal static string September {
            get {
                return ResourceManager.GetString("September", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вс.
        /// </summary>
        internal static string Sun {
            get {
                return ResourceManager.GetString("Sun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чт.
        /// </summary>
        internal static string Thu {
            get {
                return ResourceManager.GetString("Thu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вт.
        /// </summary>
        internal static string Tue {
            get {
                return ResourceManager.GetString("Tue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 
        ///(Нужно ввести по меньшей мере 2 цикла, чтобы
        ///отобразилась более точная статистика).
        /// </summary>
        internal static string TwoMinCyclesExplanation {
            get {
                return ResourceManager.GetString("TwoMinCyclesExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь был изменен.
        /// </summary>
        internal static string UserChangeSuccess {
            get {
                return ResourceManager.GetString("UserChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь удален.
        /// </summary>
        internal static string UserHasBeenDeleted {
            get {
                return ResourceManager.GetString("UserHasBeenDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нельзя удалить последнего пользователя.
        /// </summary>
        internal static string WarnLastUserDelete {
            get {
                return ResourceManager.GetString("WarnLastUserDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ср.
        /// </summary>
        internal static string Wed {
            get {
                return ResourceManager.GetString("Wed", resourceCulture);
            }
        }
    }
}
